---
title: "VNSO Trade Statistics dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    social: menu
    source_code: embed
    logo: logos/VNSO_logo_resized.svg # Note I resized to 48 pixels high to match banner height
    favicon: logos/favicon.ico
runtime: shiny
---

```{r setup, include=FALSE}
# Load required libraries
library(flexdashboard) # Dashboard layout
library(shiny) # Interactive elements
library(openxlsx) # REading excel files

# Note the repository location
repository <- file.path("..", "..")
```

Summary
=======================================================================

Row
-----------------------------------------------------------------------

### Total exports in Jan 2020 {.value-box}

```{r}
renderValueBox({
  valueBox(value = 5674, icon = "fa-area-chart")
})
```

### Total imports in Jan 2020 {.value-box}

```{r}
renderValueBox({
  valueBox(value = 10, icon = "fa-download")
})
```

### Trade balance in Jan 2020 {.value-box}

```{r}
renderValueBox({
  valueBox(value = 234, icon = "fa-users")
})
```

Row
-----------------------------------------------------------------------

### Imports/exports through time {data-width=700}

```{r}

```

### Growth in imports/exports {data-width=340}

```{r}

```

Countries
=======================================================================

Inputs {.sidebar}
-----------------------------------------------------------------------

### Select country of interest
  
Select a country from the list below to update the charts and tables on the right.

```{r}
countries <- read.csv("https://raw.githubusercontent.com/umpirsky/country-list/master/data/en_US/country.csv")[, 2]

selectInput("country", label = "Select country:",
            choices = countries, selected = "Vanuatu")
```

Row
-----------------------------------------------------------------------

### World map - imports/exports by country {data-width=700}

```{r}

```

### Imports/exports over time {data-width=340}

```{r}

```

Row
-----------------------------------------------------------------------

### Top 10 trade commodities

```{r}

```

Commodities
=======================================================================

Inputs {.sidebar}
-----------------------------------------------------------------------

### Select commodity of interest
  
Select a commodity from the list below to update the charts and tables on the right.

```{r}
principleCommodities <- read.xlsx(file.path(repository, "data", "open", "OPN_FINAL_ASY_PrincipleCommoditiesClassifications_31-01-20.xlsx"))

selectInput("type", label = "Select import or export:",
            choices = c("Import", "Export"), selected = "Import")

selectedType <- reactive({input$type})
commodities <- reactive({
  if(selectedType() == "Import"){
    return(principleCommodities$Principle.Imports)
  }else{
    return(principleCommodities$Principle.Exports)
  }
})

renderUI({
   selectInput("commodity", label = "Select commodity:",
            choices = commodities()) 
})
```

Row
-----------------------------------------------------------------------

Row
-----------------------------------------------------------------------

FAQs
=======================================================================

Data
=======================================================================

