---
title: "Trade Statistics Report"
author: "Vanuatu National Statistics Office"
date: "`r format(Sys.Date(), '%d %b %Y')`"
output:
  html_document:
    number_sections: yes
    toc: yes
    toc_depth: '2'
    toc_float: yes
  pdf_document:
    toc: yes
    toc_depth: '2'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r preparation, include=FALSE}

# Load the required libraries
library(knitr) # Nice tables
library(kableExtra) # Extra nice tables
library(dplyr) # Manipulating data
library(openxlsx) # Reading and editing excel formatted files

# Load the general R functions
source("functions.R")
```

## Importing data files

```{r import and process data}

# Read in the raw trade data
# Note that spaces in column names have been automatically replaced with "."s
tradeStatsFile <- file.path("..", "data", "secure", "SEC_PROC_ASY_RawDataAndReferenceTables_31-01-20.xlsx")
tradeStats <- read.xlsx(tradeStatsFile, sheet=1, skipEmptyRows=TRUE)

# Remove the repeated header row from the trade statistics data
tradeStats <- tradeStats[tradeStats$Office != "Office", ]

# Remove duplicated rows from the trade statistics data
duplicatedRows <- duplicated(tradeStats) 
tradeStatsNoDup <- tradeStats[duplicatedRows == FALSE, ]

# Convert the CP4 to a factor
tradeStatsNoDup$CP4 <- as.factor(tradeStats$CP4)

# Convert the statistical value to numeric
tradeStatsNoDup$Stat..Value <- as.numeric(tradeStats$Stat..Value)

# Convert excel figures to dates
tradeStatsNoDup$Reg..Date <- as.Date(as.numeric(tradeStats$Reg..Date), origin="1899-12-30") # For numeric dates excel sets origin to December 30, 1899 (https://stackoverflow.com/questions/43230470/how-to-convert-excel-date-format-to-proper-date-in-r)

# Create subset for Export and Import commodities 
tradeStatsCommodities <- tradeStatsNoDup[tradeStatsNoDup$CP4 %in% c(1000, 3071, 4000, 4071, 7100), ]

# Exclude banknotes from exports
tradeStatsNoBanknotes <- tradeStatsCommodities[tradeStatsCommodities$HS.Code != "49070010", ]

# Extract the 6, 4, and 2 digit HS codes into separate columns
tradeStatsNoBanknotes$HS.Code_6 <- extractCodeSubset(tradeStatsNoBanknotes$HS.Code, nDigits=6)
tradeStatsNoBanknotes$HS.Code_4 <- extractCodeSubset(tradeStatsNoBanknotes$HS.Code, nDigits=4)
tradeStatsNoBanknotes$HS.Code_2 <- extractCodeSubset(tradeStatsNoBanknotes$HS.Code, nDigits=2)

# Extract the 3 and 1 digit SITC codes into separate columns
tradeStatsNoBanknotes$SITC_3 <- extractCodeSubset(tradeStatsNoBanknotes$SITC, nDigits=3)
tradeStatsNoBanknotes$SITC_1 <- extractCodeSubset(tradeStatsNoBanknotes$SITC, nDigits=1)

# Create new columns for dates
tradeStatsNoBanknotes$Year<- format(tradeStatsNoBanknotes$Reg..Date, format= "%Y")
tradeStatsNoBanknotes$Month<- format(tradeStatsNoBanknotes$Reg..Date, format= "%B")
tradeStatsNoBanknotes$Day<- format(tradeStatsNoBanknotes$Reg..Date, format= "%d")

# Quality check indicators (Wgt..Net and Stat..Value) 
#tradeStatsNoBanknotes$Wgt..Net <- as.numeric(tradeStatsNoBanknotes$Wgt..Net) # Convert the net weight to numeric
#tradeStatsNoBanknotes$PricePerUnit<- tradeStatsNoBanknotes$Stat..Value/tradeStatsNoBanknotes$Wgt..Net # Create new column 
#tradeStatsCommoditiesSorted<- tradeStatsNoBanknotes[order(-tradeStatsNoBanknotes$Stat..Value), ] # Sort the stats value in descending order (this isn't working)

# Store principle exports and imports 


# Merge classifications 
tradeStatsFileMergeTransport <- file.path("..", "data", "open", "OPN_FINAL_ASY_ModeOfTransportClassifications_31-01-20.xlsx") # Mode of Transport
modeOfTransport <- read.xlsx(tradeStatsFileMergeTransport, sheet=1, skipEmptyRows=TRUE)
mergedModeOfTransport<- merge(modeOfTransport, tradeStatsNoBanknotes, by= "Office")

tradeStatsFileMergeHSCode <- file.path("..", "data", "open", "OPN_FINAL_ASY_HSCodeClassifications_31-01-20.xlsx") # HS codes
hsDescription <- read.xlsx(tradeStatsFileMergeHSCode, sheet=1, skipEmptyRows=TRUE)
mergedHSCode<- merge(hsDescription, mergedModeOfTransport, by= "HS.Code_2")

tradeStatsFileMergeSITCCode <- file.path("..", "data", "open", "OPN_FINAL_ASY_SITCCodeClassifications_31-01-20.xlsx") # Country of origin
sitcDescription <- read.xlsx(tradeStatsFileMergeSITCCode, sheet=1, skipEmptyRows=TRUE)
mergedSITCDescription<- merge(sitcDescription, mergedHSCode, by= "SITC_1")

tradeStatsFileMergePrincipleCommodities <- file.path("..", "data", "open", "OPN_FINAL_ASY_PrincipleCommoditiesClassifications_31-01-20.xlsx") # Country of origin
principleCommodties <- read.xlsx(tradeStatsFileMergePrincipleCommodities, sheet=1, skipEmptyRows=TRUE)
mergedPrincipleCommodties<- merge(principleCommodties, mergedSITCDescription, by= "HS.Code")

duplicatedRowsMergedPrincipleCommodties <- which(duplicated(mergedPrincipleCommodties))
duplicatedRowsMergedPrincipleCommodties
mergedPrincipleCommoditiesNoDup <- mergedPrincipleCommodties[-duplicatedRowsMergedPrincipleCommodties, ]

tradeStatsFileMergeCountryDesImports <- file.path("..", "data", "open", "OPN_FINAL_ASY_CountryDescriptionImportClassifications_31-01-20.xlsx") # Country of origin (CO)
countryDescritpionImports <- read.xlsx(tradeStatsFileMergeCountryDesImports, sheet=1, skipEmptyRows=TRUE)
mergedCountryOrigin<- merge(countryDescritpionImports, mergedPrincipleCommoditiesNoDup, by= "CO")

tradeStatsFileMergeCountryDesExports <- file.path("..", "data", "open", "OPN_FINAL_ASY_CountryDescriptionExportClassifications_31-01-20.xlsx") 
countryDescritpionExports <- read.xlsx(tradeStatsFileMergeCountryDesExports, sheet=1, skipEmptyRows=TRUE)
mergedCountryExport<- merge(countryDescritpionExports, mergedCountryOrigin, by= "CE/CD")

tradeStatsFileMergeBECDescriptions <- file.path("..", "data", "open", "OPN_FINAL_ASY_BECClassifications_31-01-20.xlsx") # Broad economic categories
becDescriptions <- read.xlsx(tradeStatsFileMergeBECDescriptions, sheet=1, skipEmptyRows=TRUE)
mergedBECDescriptions<- merge(becDescriptions, mergedCountryExport, by= "HS.Code_6")


# New HS codes and SITC codes stored and we are notified


# Processed data set stored
processedTradeStats<- mergedBECDescriptions

```

## Balance of Trade
```{r calculate balance of trade statistics with base R, eval=FALSE, echo=FALSE}

# Calculate the balance of trade statistics - note that this remove a bit of redundancy
exports <- sum(processedTradeStats[processedTradeStats$CP4 == 1000, "Stat..Value"], na.rm=TRUE) # Added na.rm in case NAs introduced at later date
reExports <- sum(processedTradeStats[processedTradeStats$CP4 == 3071, "Stat..Value"], na.rm=TRUE)
totalExports <- exports + reExports
imports <- sum(processedTradeStats[processedTradeStats$CP4 %in% c(4000, 4071, 7100), "Stat..Value"], na.rm=TRUE)
balance <- totalExports - imports

# Insert values into table
tradeBalance <- data.frame("Export"=exports, "Re-Export"=reExports, "Total Export"=totalExports, "Imports CIF"=imports, "Trade Balance"=balance)

prettyTable(tradeBalance)
```

```{r insert balance of trade statistics into final formatted table}

# Extremely helpful resource for openxlsx here: https://rdrr.io/cran/openxlsx/

# Note current year and month of data
fileNameParts <- strsplit(tradeStatsFile, split="_")[[1]]
date <- as.Date(strsplit(fileNameParts[length(fileNameParts)], split="\\.")[[1]][1], format="%d-%m-%y")
month <- format(date, "%B")
year <- format(date, "%Y")

# Note the excel workbook containing the final formmatted tables
finalWorkbookFileName <- file.path("..", "outputs", "SEC_FINAL_MAN_FinalTradeStatisticsTables_31-01-20.xlsx")

## Updating the Annual and Monthly sub tables
# Extract the balance of trade data and extract sub tables
balanceOfTradeSubTables <- extractHistoricBalanceOfTradeStatistics(finalWorkbookFileName)

# Update the sub tables for the balance of trade data
balanceOfTradeSubTables <- updateBalanceOfTradeSubTables(balanceOfTradeSubTables, month, year, tradeBalance/1000000)

## Editing the final formatted tables
updatedFinalFormattedBalanceOfTradeTable(finalWorkbookFileName, balanceOfTradeSubTables)
```


## Import by HS Code
```{r calculate import by HS Code statistics with base R, eval=FALSE, echo=FALSE}

# Define the CP4 codes need for table
codesCP4 <- c(4000, 4071, 7100)

# Define the categories used for each column
categoryColumn <- "HS.Code_2"
columnCategories <- list(
  animalProductsImports=c("01", "02", "03", "04", "05"),
  vegetableProductsImports=c("06", "07", "08", "09", "10", "11", "12", "13", "14"),
  animalOrVegtableProductsImports=c("15"),
  preparedFoodstuffsImports=c("16", "17", "18", "19", "20", "21", "22", "23", "24"),
  mineralProductsImports=c("25", "26", "27"),
  chemicalProductsImports=c("28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38"),
  platsicThereofImports=c("39", "40"),
  rawHidesImports=c("41", "42", "43"),
  woodMaterialImports=c("44", "45", "46"),
  woodThereofImports=c("47", "48", "49"),
  textileArticlesImports=c("50", "51", "52", "53", "54", "55", "56", "57", "58", "59", "60", "61", "62", "63"),
  footwearThereofImports=c("64", "65", "66", "67"),
  articlesStoneImports=c("68", "69", "70"),
  pearlsStoneImports=c("71"),
  baseMetalsImports=c("72", "73", "74", "75", "76", "77", "78", "79", "80", "81", "82", "83"),
  machineryThereofImports=c("84", "85"),
  vehiclesEquipmentImports=c("86", "87", "88", "89"),
  photographicGoodsImports=c("90", "91", "92"),
  armsThereofImports=c("93"),
  miscellaneousArticlesImports=c("94", "95", "96"),
  worksArtImports=c("97"),
  othersImports=c("98", "99")
)

# Build the table
importsByHS <- buildRawSummaryTable(processTradeStats, codesCP4, categoryColumn, columnCategories)

# Add full names into columns
colnames(importsByHS) <- c(
  "Live animals: animal products", 
  "Vegetable products", 
  "Animal or vegetable oils & fats", 
  "Prepared foodstuffs, beverages, spirits & tobacco", 
  "Mineral products", 
  "Chemicals and allied products", 
  "Plastic, rubber & articles thereof", 
  "Raw hides, skins, leather articles & travel goods", 
  "Wood, cork & articles thereof & plaiting material", 
  "Wood pulp, paper & paperboard & articles thereof", 
  "Textiles & textile articles", 
  "Footwear, headgear, umbrellas & parts thereof", 
  "Articles of stone, plaster, cement, glass & ceremic products", 
  "Pearls, precious & semi-precious stones & metals", 
  "Base metals & articles thereof", 
  "Machinery & mechanical & electrical appliances & parts thereof", 
  "Vehicles, aircraft & associated transport equipment", 
  "Photographic & optical, medical & surgical goods & clocks/watches & musical instruments", 
  "Arms and ammunition, parts & accessories thereof", 
  "Miscellaneous manufactured articles", 
  "Works of art, collectors pieces & antiques", 
  "Others", 
  "Total")

# View the table
prettyTable(importsByHS)

```


```{r insert Import by HS Code into final formatted table}


```

## Export by HS Code

```{r calculate export by HS Code statistics with base R, eval=FALSE, echo=FALSE}

# Calculate the Export by HS Code
animalProductsExports <- calculateStatValueSum(processedTradeStats, codes_CP4 = c(1000), categoryCol = "HS.Code_2", categoryValues = c("01", "02", "03", "04", "05"))

vegtableProductsExports <- calculateStatValueSum(processedTradeStats, codes_CP4 = c(1000), categoryCol = "HS.Code_2", categoryValues = c("06", "07", "08", "09", "10", "11", "12", "13", "14"))

animalOrVegtableProductsExports <- calculateStatValueSum(processedTradeStats, codes_CP4 = c(1000), categoryCol = "HS.Code_2", categoryValues = c("15"))

preparedFoodstuffsExports <- calculateStatValueSum(processedTradeStats, codes_CP4 = c(1000), categoryCol = "HS.Code_2", categoryValues = c("16", "17", "18", "19", "20", "21", "22", "23", "24"))

mineralProductsExports <- calculateStatValueSum(processedTradeStats, codes_CP4 = c(1000), categoryCol = "HS.Code_2", categoryValues = c("25", "26", "27"))

chemicalProductsExports <- calculateStatValueSum(processedTradeStats, codes_CP4 = c(1000), categoryCol = "HS.Code_2", categoryValues = c("28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38"))

platsicThereofExports <- calculateStatValueSum(processedTradeStats, codes_CP4 = c(1000), categoryCol = "HS.Code_2", categoryValues = c("39", "40"))

rawHidesExports <- calculateStatValueSum(processedTradeStats, codes_CP4 = c(1000), categoryCol = "HS.Code_2", categoryValues = c("41", "42", "43"))

woodMaterialExports <- calculateStatValueSum(processedTradeStats, codes_CP4 = c(1000), categoryCol = "HS.Code_2", categoryValues = c("44", "45", "46"))

woodThereofExports <- calculateStatValueSum(processedTradeStats, codes_CP4 = c(1000), categoryCol = "HS.Code_2", categoryValues = c("47", "48", "49"))

textileArticlesExports <- calculateStatValueSum(processedTradeStats, codes_CP4 = c(1000), categoryCol = "HS.Code_2", categoryValues = c("50", "51", "52", "53", "54", "55", "56", "57", "58", "59", "60", "61", "62", "63"))

footwearThereofExports <- calculateStatValueSum(processedTradeStats, codes_CP4 = c(1000), categoryCol = "HS.Code_2", categoryValues = c("64", "65", "66", "67"))

articlesStoneExports <- calculateStatValueSum(processedTradeStats, codes_CP4 = c(1000), categoryCol = "HS.Code_2", categoryValues = c("68", "69", "70"))

pearlsStoneExports <- calculateStatValueSum(processedTradeStats, codes_CP4 = c(1000), categoryCol = "HS.Code_2", categoryValues = c("71"))

baseMetalsExports <- calculateStatValueSum(processedTradeStats, codes_CP4 = c(1000), categoryCol = "HS.Code_2", categoryValues = c("72", "73", "74", "75", "76", "77", "78", "79", "80", "81", "82", "83"))

machineryThereofExports <- calculateStatValueSum(processedTradeStats, codes_CP4 = c(1000), categoryCol = "HS.Code_2", categoryValues = c("84", "85"))

vehiclesEquipmentExports <- calculateStatValueSum(processedTradeStats, codes_CP4 = c(1000), categoryCol = "HS.Code_2", categoryValues = c("86", "87", "88", "89"))

photographicGoodsExports <- calculateStatValueSum(processedTradeStats, codes_CP4 = c(1000), categoryCol = "HS.Code_2", categoryValues = c("90", "91", "92"))

armsThereofExports <- calculateStatValueSum(processedTradeStats, codes_CP4 = c(1000), categoryCol = "HS.Code_2", categoryValues = c("93"))

miscellaneousArticlesExports <- calculateStatValueSum(processedTradeStats, codes_CP4 = c(1000), categoryCol = "HS.Code_2", categoryValues = c("94", "95", "96"))

worksArtExports <- calculateStatValueSum(processedTradeStats, codes_CP4 = c(1000), categoryCol = "HS.Code_2", categoryValues = c("97"))

othersExports <- calculateStatValueSum(processedTradeStats, codes_CP4 = c(1000), categoryCol = "HS.Code_2", categoryValues = c("98", "99"))

totalExportsByHSCode<- animalProductsExports + vegtableProductsExports + animalOrVegtableProductsExports + preparedFoodstuffsExports + mineralProductsExports + chemicalProductsExports + platsicThereofExports + rawHidesExports + woodMaterialExports + woodThereofExports + textileArticlesExports + footwearThereofExports + articlesStoneExports + pearlsStoneExports + baseMetalsExports + machineryThereofExports + vehiclesEquipmentExports + photographicGoodsExports + armsThereofExports + miscellaneousArticlesExports + worksArtExports + othersExports

# Insert values into table
exportsByHS <- data.frame("Live animals: animal products"=animalProductsExports, 
"Vegetable products"=vegtableProductsExports, 
"Animal or vegetable oils & fats"=animalOrVegtableProductsExports, 
"Prepared foodstuffs, beverages, spirits & tobacco"=preparedFoodstuffsExports, 
"Mineral products"=mineralProductsExports, 
"Chemicals and allied products"= chemicalProductsExports, 
"Plastic, rubber & articles thereof"= platsicThereofExports, 
"Raw hides, skins, leather articles & travel goods"= rawHidesExports, 
"Wood, cork & articles thereof & plaiting material"= woodMaterialExports, 
"Wood pulp, paper & paperboard & articles thereof"= woodThereofExports, 
"Textiles & textile articles"= textileArticlesExports, 
"Footwear, headgear, umbrellas & parts thereof"= footwearThereofExports, 
"Articles of stone, plaster, cement, glass & ceremic products"= articlesStoneExports, 
"Pearls, precious & semi-precious stones & metals"= pearlsStoneExports, 
"Base metals & articles thereof"= baseMetalsExports, 
"Machinery & mechanical & electrical appliances & parts thereof"= machineryThereofExports, 
"Vehicles, aircraft & associated transport equipment"= vehiclesEquipmentExports, 
"Photographic & optical, medical & surgical goods & clocks/watches & musical instruments"= photographicGoodsExports, 
"Arms and ammunition, parts & accessories thereof"= armsThereofExports, 
"Miscellaneous manufactured articles"= miscellaneousArticlesExports, 
"Works of art, collectors pieces & antiques"= worksArtExports, 
"Others"= othersExports, 
"Total"= totalExportsByHSCode)

prettyTable(exportsByHS)

```

```{r insert Export by HS Code into final formatted table}


```


## Re-Export by HS Code

```{r calculate re-export by HS Code statistics with base R, eval=FALSE, echo=FALSE}

# Calculate the Re-Export by HS Code

animalProductsReExports <- calculateStatValueSum(processedTradeStats, codes_CP4 = c(3071), categoryCol = "HS.Code_2", categoryValues = c("01", "02", "03", "04", "05"))

vegtableProductsReExports <- calculateStatValueSum(processedTradeStats, codes_CP4 = c(3071), categoryCol = "HS.Code_2", categoryValues = c("06", "07", "08", "09", "10", "11", "12", "13", "14"))

animalOrVegtableProductsReExports <- calculateStatValueSum(processedTradeStats, codes_CP4 = c(3071), categoryCol = "HS.Code_2", categoryValues = c("15"))

preparedFoodstuffsReExports <- calculateStatValueSum(processedTradeStats, codes_CP4 = c(3071), categoryCol = "HS.Code_2", categoryValues = c("16", "17", "18", "19", "20", "21", "22", "23", "24"))

mineralProductsReExports <- calculateStatValueSum(processedTradeStats, codes_CP4 = c(3071), categoryCol = "HS.Code_2", categoryValues = c("25", "26", "27"))

chemicalProductsReExports <- calculateStatValueSum(processedTradeStats, codes_CP4 = c(3071), categoryCol = "HS.Code_2", categoryValues = c("28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38"))

platsicThereofReExports <- calculateStatValueSum(processedTradeStats, codes_CP4 = c(3071), categoryCol = "HS.Code_2", categoryValues = c("39", "40"))

rawHidesReExports <- calculateStatValueSum(processedTradeStats, codes_CP4 = c(3071), categoryCol = "HS.Code_2", categoryValues = c("41", "42", "43"))

woodMaterialReExports <- calculateStatValueSum(processedTradeStats, codes_CP4 = c(3071), categoryCol = "HS.Code_2", categoryValues = c("44", "45", "46"))

woodThereofReExports <- calculateStatValueSum(processedTradeStats, codes_CP4 = c(3071), categoryCol = "HS.Code_2", categoryValues = c("47", "48", "49"))

textileArticlesReExports <- calculateStatValueSum(processedTradeStats, codes_CP4 = c(3071), categoryCol = "HS.Code_2", categoryValues = c("50", "51", "52", "53", "54", "55", "56", "57", "58", "59", "60", "61", "62", "63"))

footwearThereofReExports <- calculateStatValueSum(processedTradeStats, codes_CP4 = c(3071), categoryCol = "HS.Code_2", categoryValues = c("64", "65", "66", "67"))

articlesStoneReExports <- calculateStatValueSum(processedTradeStats, codes_CP4 = c(3071), categoryCol = "HS.Code_2", categoryValues = c("68", "69", "70"))

pearlsStoneReExports <- calculateStatValueSum(processedTradeStats, codes_CP4 = c(3071), categoryCol = "HS.Code_2", categoryValues = c("71"))

baseMetalsReExports <- calculateStatValueSum(processedTradeStats, codes_CP4 = c(3071), categoryCol = "HS.Code_2", categoryValues = c("72", "73", "74", "75", "76", "77", "78", "79", "80", "81", "82", "83"))

machineryThereofReExports <- calculateStatValueSum(processedTradeStats, codes_CP4 = c(3071), categoryCol = "HS.Code_2", categoryValues = c("84", "85"))

vehiclesEquipmentReExports <- calculateStatValueSum(processedTradeStats, codes_CP4 = c(3071), categoryCol = "HS.Code_2", categoryValues = c("86", "87", "88", "89"))

photographicGoodsReExports <- calculateStatValueSum(processedTradeStats, codes_CP4 = c(3071), categoryCol = "HS.Code_2", categoryValues = c("90", "91", "92"))

armsThereofReExports <- calculateStatValueSum(processedTradeStats, codes_CP4 = c(3071), categoryCol = "HS.Code_2", categoryValues = c("93"))

miscellaneousArticlesReExports <- calculateStatValueSum(processedTradeStats, codes_CP4 = c(3071), categoryCol = "HS.Code_2", categoryValues = c("94", "95", "96"))

worksArtReExports <- calculateStatValueSum(processedTradeStats, codes_CP4 = c(3071), categoryCol = "HS.Code_2", categoryValues = c("97"))

othersReExports <- calculateStatValueSum(processedTradeStats, codes_CP4 = c(3071), categoryCol = "HS.Code_2", categoryValues = c("98", "99"))

totalReExportsByHSCode<- animalProductsReExports + vegtableProductsReExports + animalOrVegtableProductsReExports + preparedFoodstuffsReExports + mineralProductsReExports + chemicalProductsReExports + platsicThereofReExports + rawHidesReExports + woodMaterialReExports + woodThereofReExports + textileArticlesReExports + footwearThereofReExports + articlesStoneReExports + pearlsStoneReExports + baseMetalsReExports + machineryThereofReExports + vehiclesEquipmentReExports + photographicGoodsReExports + armsThereofReExports + miscellaneousArticlesReExports + worksArtReExports + othersReExports

# Insert values into table
reExportsByHS <- data.frame("Live animals: animal products"=animalProductsReExports, 
"Vegetable products"=vegtableProductsReExports, 
"Animal or vegetable oils & fats"=animalOrVegtableProductsReExports, 
"Prepared foodstuffs, beverages, spirits & tobacco"=preparedFoodstuffsReExports, 
"Mineral products"=mineralProductsReExports, 
"Chemicals and allied products"= chemicalProductsReExports, 
"Plastic, rubber & articles thereof"= platsicThereofReExports, 
"Raw hides, skins, leather articles & travel goods"= rawHidesReExports, 
"Wood, cork & articles thereof & plaiting material"= woodMaterialReExports, 
"Wood pulp, paper & paperboard & articles thereof"= woodThereofReExports, 
"Textiles & textile articles"= textileArticlesReExports, 
"Footwear, headgear, umbrellas & parts thereof"= footwearThereofReExports, 
"Articles of stone, plaster, cement, glass & ceremic products"= articlesStoneReExports, 
"Pearls, precious & semi-precious stones & metals"= pearlsStoneReExports, 
"Base metals & articles thereof"= baseMetalsReExports, 
"Machinery & mechanical & electrical appliances & parts thereof"= machineryThereofReExports, 
"Vehicles, aircraft & associated transport equipment"= vehiclesEquipmentReExports, 
"Photographic & optical, medical & surgical goods & clocks/watches & musical instruments"= photographicGoodsReExports, 
"Arms and ammunition, parts & accessories thereof"= armsThereofReExports, 
"Miscellaneous manufactured articles"= miscellaneousArticlesReExports, 
"Works of art, collectors pieces & antiques"= worksArtReExports, 
"Others"= othersReExports, 
"Total"= totalReExportsByHSCode)

prettyTable(reExportsByHS)

```

```{r insert Re-Export by HS Code into final formatted table}

```


## Total Exports by HS Code

```{r calculate total exports by HS Code statistics with base R, eval=FALSE, echo=FALSE}

# Insert values into table
totalExportsByHS <- exportsByHS + reExportsByHS

prettyTable(totalExportsByHS)

```

```{r insert Total Exports by HS Code into final formatted table}

```

## Principle Exports

```{r calculate principle exports statistics with base R, eval=FALSE, echo=FALSE}

# Calculate the principle Exports 

alcoholicDrinksExports <- calculateStatValueSum(processedTradeStats, codes_CP4 = c(1000), categoryCol = "PRINCIPAL.EXPORTS", categoryValues = c("ALCOHOLIC DRINKS"))

beefExports <- calculateStatValueSum(processedTradeStats, codes_CP4 = c(1000), categoryCol = "PRINCIPAL.EXPORTS", categoryValues = c("BEEF"))

cocoaExports <- calculateStatValueSum(processedTradeStats, codes_CP4 = c(1000), categoryCol = "PRINCIPAL.EXPORTS", categoryValues = c("COCOA"))

copraMealExports <- calculateStatValueSum(processedTradeStats, codes_CP4 = c(1000), categoryCol = "PRINCIPAL.EXPORTS", categoryValues = c("COPRA MEAL"))

coconutOilExports <- calculateStatValueSum(processedTradeStats, codes_CP4 = c(1000), categoryCol = "PRINCIPAL.EXPORTS", categoryValues = c("COCONUT OIL"))

coffeeAllTypesExports <- calculateStatValueSum(processedTradeStats, codes_CP4 = c(1000), categoryCol = "PRINCIPAL.EXPORTS", categoryValues = c("COFFEE"))

copraExports <- calculateStatValueSum(processedTradeStats, codes_CP4 = c(1000), categoryCol = "PRINCIPAL.EXPORTS", categoryValues = c("COPRA"))

cowhidesExports <- calculateStatValueSum(processedTradeStats, codes_CP4 = c(1000), categoryCol = "PRINCIPAL.EXPORTS", categoryValues = c("COWHIDES"))

fishTunaExports <- calculateStatValueSum(processedTradeStats, codes_CP4 = c(1000), categoryCol = "PRINCIPAL.EXPORTS", categoryValues = c("TUNA FISH"))

kavaExports <- calculateStatValueSum(processedTradeStats, codes_CP4 = c(1000), categoryCol = "PRINCIPAL.EXPORTS", categoryValues = c("KAVA"))

ornamentalFishExports <- calculateStatValueSum(processedTradeStats, codes_CP4 = c(1000), categoryCol = "PRINCIPAL.EXPORTS", categoryValues = c("LIFE FISH"))

woodArticlesExports <- calculateStatValueSum(processedTradeStats, codes_CP4 = c(1000), categoryCol = "PRINCIPAL.EXPORTS", categoryValues = c("WOOD"))

shellButtonsExports <- calculateStatValueSum(processedTradeStats, codes_CP4 = c(1000), categoryCol = "PRINCIPAL.EXPORTS", categoryValues = c("SHELL BUTTONS"))

vanillaExports <- calculateStatValueSum(processedTradeStats, codes_CP4 = c(1000), categoryCol = "PRINCIPAL.EXPORTS", categoryValues = c("VANILLA"))

otherProductsExports <- calculateStatValueSum(processedTradeStats, codes_CP4 = c(1000), categoryCol = "PRINCIPAL.EXPORTS", categoryValues = c("OTHER PRODUCTS"))

totalPExports<- alcoholicDrinksExports + beefExports + cocoaExports + copraMealExports + coconutOilExports + coffeeAllTypesExports + copraExports + cowhidesExports + fishTunaExports + kavaExports + ornamentalFishExports + woodArticlesExports + shellButtonsExports + vanillaExports + otherProductsExports

# Insert values into table
totalPrincipleExports <- data.frame("Alcoholic Drinks"=alcoholicDrinksExports, 
                            "Beef fresh, chilled, frozen and preserved"=beefExports, 
                            "Cocoa"=cocoaExports, 
                            "Copra Meal"=copraMealExports, 
                            "Coconut oil"=coconutOilExports, 
                            "Coffee, all types"= coffeeAllTypesExports,
                            "Copra"= copraExports, 
                            "Cowhides"= cowhidesExports, 
                            "Fish: Tuna"= fishTunaExports, 
                            "Kava"= kavaExports, 
                            "Ornamental fish"= ornamentalFishExports, 
                            "Wood and articles of wood; wood charcoal"= woodArticlesExports, 
                            "Shell buttons"= shellButtonsExports, 
                            "Vanilla"= vanillaExports, 
                            "Other products"= otherProductsExports, 
                            "Total exports"= totalPExports) 

prettyTable(totalPrincipleExports)


# Calculate the principle Re-Exports 

alcoholicDrinksReExports <- calculateStatValueSum(processedTradeStats, codes_CP4 = c(3071), categoryCol = "PRINCIPAL.EXPORTS", categoryValues = c("ALCOHOLIC DRINKS"))

tobaccoReExports <- calculateStatValueSum(processedTradeStats, codes_CP4 = c(3071), categoryCol = "PRINCIPAL.EXPORTS", categoryValues = c("CIGARETTES containing tobacco"))

fuelReExports <- calculateStatValueSum(processedTradeStats, codes_CP4 = c(3071), categoryCol = "PRINCIPAL.EXPORTS", categoryValues = c("FUEL"))

otherProductsReExports<- calculateStatValueSum(processedTradeStats, codes_CP4 = c(3071), categoryCol = "PRINCIPAL.EXPORTS", categoryValues = c("OTHER PRODUCTS"))

totalPReExports<- alcoholicDrinksReExports + tobaccoReExports + fuelReExports + otherReProductsReExports 

# Insert values into table
totalPrincipleReExports <- data.frame("Alcoholic Drinks"=alcoholicDrinksReExports, 
                              "Tobacco and cigarettes"=tobaccoReExports, 
                              "Fuel"=fuelReExports, 
                              "Other products"=otherProductsReExports, 
                              "Total re-exports"=totalPReExports) 

prettyTable(totalPrincipleRePExports)

# Total Exports and Re-Exports
totalPrincipleExportsandReExports <- totalPExports + totalPReExports

prettyTable(totalPrincipleExportsandReExports)

```

```{r insert Principle Exports into final formatted table}

```


## Principle Imports

```{r calculate principle imports statistics with base R, eval=FALSE, echo=FALSE}

# Calculate the principle Imports 
meatPrincipleImports <- calculateStatValueSum(processedTradeStats, codes_CP4 = c(4000, 4071, 7100), categoryCol = "PRINCIPAL.IMPORTS", categoryValues = c("Meat and edible offal of poultry"))

fishPrincipleImports <- calculateStatValueSum(processedTradeStats, codes_CP4 = c(4000, 4071, 7100), categoryCol = "PRINCIPAL.IMPORTS", categoryValues = c("Fish and crustaceans, molluscs and other aquatic invertebrates"))

milkPrincipleImports <- calculateStatValueSum(processedTradeStats, codes_CP4 = c(4000, 4071, 7100), categoryCol = "PRINCIPAL.IMPORTS", categoryValues = c("Milk and Cream"))

ricePrincipleImports <- calculateStatValueSum(processedTradeStats, codes_CP4 = c(4000, 4071, 7100), categoryCol = "PRINCIPAL.IMPORTS", categoryValues = c("RICE"))

wheatPrincipleImports <- calculateStatValueSum(processedTradeStats, codes_CP4 = c(4000, 4071, 7100), categoryCol = "PRINCIPAL.IMPORTS", categoryValues = c("Wheat or meslin flour"))

preparedMeatPrincipleImports <- calculateStatValueSum(processedTradeStats, codes_CP4 = c(4000, 4071, 7100), categoryCol = "PRINCIPAL.IMPORTS", categoryValues = c("Other prepared or preserved meat, meat offal or blood"))

preparedFishPrincipleImports <- calculateStatValueSum(processedTradeStats, codes_CP4 = c(4000, 4071, 7100), categoryCol = "PRINCIPAL.IMPORTS", categoryValues = c("Prepared or preserved fish"))

sugarPrincipleImports <- calculateStatValueSum(processedTradeStats, codes_CP4 = c(4000, 4071, 7100), categoryCol = "PRINCIPAL.IMPORTS", categoryValues = c("Sugar"))

pastaPrincipleImports <- calculateStatValueSum(processedTradeStats, codes_CP4 = c(4000, 4071, 7100), categoryCol = "PRINCIPAL.IMPORTS", categoryValues = c("Pasta, whether cooked or stuffed or otherwise prepared, such as spaghetti, macaroni, noodles, lasagne, gnocchi, ravioli, cannelloni; couscous"))

preparedFoodsPrincipleImports <- calculateStatValueSum(processedTradeStats, codes_CP4 = c(4000, 4071, 7100), categoryCol = "PRINCIPAL.IMPORTS", categoryValues = c("Prepared foods obtained by the swelling or roasting of cereals or cereal products eg corn flakes; cereals (excl maize) in grain or flakes"))

breadPrincipleImports <- calculateStatValueSum(processedTradeStats, codes_CP4 = c(4000, 4071, 7100), categoryCol = "PRINCIPAL.IMPORTS", categoryValues = c("Bread, pastry, cakes, biscuits and other bakers' wares"))

nonAlcoholicPrincipleImports <- calculateStatValueSum(processedTradeStats, codes_CP4 = c(4000, 4071, 7100), categoryCol = "PRINCIPAL.IMPORTS", categoryValues = c("Non-alcoholic drinks including mineral water"))

alcoholicPrincipleImports <- calculateStatValueSum(processedTradeStats, codes_CP4 = c(4000, 4071, 7100), categoryCol = "PRINCIPAL.IMPORTS", categoryValues = c("ALCOHOLIC DRINKS"))

animalFeedingPrincipleImports <- calculateStatValueSum(processedTradeStats, codes_CP4 = c(4000, 4071, 7100), categoryCol = "PRINCIPAL.IMPORTS", categoryValues = c("Preparations of a kind used in animal feeding"))

tobaccoProductsPrincipleImports <- calculateStatValueSum(processedTradeStats, codes_CP4 = c(4000, 4071, 7100), categoryCol = "PRINCIPAL.IMPORTS", categoryValues = c("Cigars, cheroots, cigarillos and cigarettes, of tobacco or of tobacco substitutes"))

cementPrincipleImports <- calculateStatValueSum(processedTradeStats, codes_CP4 = c(4000, 4071, 7100), categoryCol = "PRINCIPAL.IMPORTS", categoryValues = c("Portland cement, aluminous cement, slag cement, supersulphate cement and similar hydraulic cements"))

cementPrincipleImports <- calculateStatValueSum(processedTradeStats, codes_CP4 = c(4000, 4071, 7100), categoryCol = "PRINCIPAL.IMPORTS", categoryValues = c("Portland cement, aluminous cement, slag cement, supersulphate cement and similar hydraulic cements"))

petroleumPrincipleImports <- calculateStatValueSum(processedTradeStats, codes_CP4 = c(4000, 4071, 7100), categoryCol = "PRINCIPAL.IMPORTS", categoryValues = c("Petroleum oils and oils obtained from bituminous minerals"))

hydrocarbonsPrincipleImports <- calculateStatValueSum(processedTradeStats, codes_CP4 = c(4000, 4071, 7100), categoryCol = "PRINCIPAL.IMPORTS", categoryValues = c("Petroleum gases and other gaseous hydrocarbons"))

medicamentsPrincipleImports <- calculateStatValueSum(processedTradeStats, codes_CP4 = c(4000, 4071, 7100), categoryCol = "PRINCIPAL.IMPORTS", categoryValues = c("Medicaments"))

perfumesPrincipleImports <- calculateStatValueSum(processedTradeStats, codes_CP4 = c(4000, 4071, 7100), categoryCol = "PRINCIPAL.IMPORTS", categoryValues = c("Perfumes, make-up preparations and preparations for the care of the skin (excl medicaments) and products for hair"))

pipesPrincipleImports <- calculateStatValueSum(processedTradeStats, codes_CP4 = c(4000, 4071, 7100), categoryCol = "PRINCIPAL.IMPORTS", categoryValues = c("Tubes, pipes and hoses, and fittings therefor (for example, joints, elbows, flanges), of plastics."))

lidsPrincipleImports <- calculateStatValueSum(processedTradeStats, codes_CP4 = c(4000, 4071, 7100), categoryCol = "PRINCIPAL.IMPORTS", categoryValues = c("Articles for the conveyance or packing of goods; stoppers, lids, caps and other closures, of plastics"))

tiresPrincipleImports <- calculateStatValueSum(processedTradeStats, codes_CP4 = c(4000, 4071, 7100), categoryCol = "PRINCIPAL.IMPORTS", categoryValues = c("New pneumatic tires, of rubber"))

woodPrincipleImports <- calculateStatValueSum(processedTradeStats, codes_CP4 = c(4000, 4071, 7100), categoryCol = "PRINCIPAL.IMPORTS", categoryValues = c("Wood sawn or chipped lengthwise, sliced or peeled, whether or not planed, sanded or end-jointed"))

toiletPaperPrincipleImports <- calculateStatValueSum(processedTradeStats, codes_CP4 = c(4000, 4071, 7100), categoryCol = "PRINCIPAL.IMPORTS", categoryValues = c("Toilet paper and similar paper"))

printedBooksPrincipleImports <- calculateStatValueSum(processedTradeStats, codes_CP4 = c(4000, 4071, 7100), categoryCol = "PRINCIPAL.IMPORTS", categoryValues = c("Printed books, brochures, leaflets and similar printed matter"))

clothingPrincipleImports <- calculateStatValueSum(processedTradeStats, codes_CP4 = c(4000, 4071, 7100), categoryCol = "PRINCIPAL.IMPORTS", categoryValues = c("Articles of apparel and clothing accessories"))

textileClothingPrincipleImports <- calculateStatValueSum(processedTradeStats, codes_CP4 = c(4000, 4071, 7100), categoryCol = "PRINCIPAL.IMPORTS", categoryValues = c("Other made up textile articles; sets; worn clothing and worn textile articles; rags"))

footwearPrincipleImports <- calculateStatValueSum(processedTradeStats, codes_CP4 = c(4000, 4071, 7100), categoryCol = "PRINCIPAL.IMPORTS", categoryValues = c("Footwear, gaiters and the like; parts of such articles"))

ironSteelPrincipleImports <- calculateStatValueSum(processedTradeStats, codes_CP4 = c(4000, 4071, 7100), categoryCol = "PRINCIPAL.IMPORTS", categoryValues = c("Iron and steel"))

articlesIronSteelPrincipleImports <- calculateStatValueSum(processedTradeStats, codes_CP4 = c(4000, 4071, 7100), categoryCol = "PRINCIPAL.IMPORTS", categoryValues = c("Articles of iron or steel"))

aluminiumThereofPrincipleImports <- calculateStatValueSum(processedTradeStats, codes_CP4 = c(4000, 4071, 7100), categoryCol = "PRINCIPAL.IMPORTS", categoryValues = c("Aluminium and articles thereof"))
 
enginesThereofPrincipleImports <- calculateStatValueSum(processedTradeStats, codes_CP4 = c(4000, 4071, 7100), categoryCol = "PRINCIPAL.IMPORTS", categoryValues = c("Spark-ignition reciprocating or rotary internal combustion piston engines and compression-ignition internal combustion piston engines (diesel or semi-diesel engines)"))
 
refridgeratorsPrincipleImports <- calculateStatValueSum(processedTradeStats, codes_CP4 = c(4000, 4071, 7100), categoryCol = "PRINCIPAL.IMPORTS", categoryValues = c("Refrigerators, freezers and other refrigerating or freezing equipment, electric or other; heat pumps other than air conditioning machines"))

purifyingMachineryPrincipleImports <- calculateStatValueSum(processedTradeStats, codes_CP4 = c(4000, 4071, 7100), categoryCol = "PRINCIPAL.IMPORTS", categoryValues = c("Centrifuges, including centrifugal dryers; filtering or purifying machinery and apparatus, for liquids or gases"))

bulldozersPrincipleImports <- calculateStatValueSum(processedTradeStats, codes_CP4 = c(4000, 4071, 7100), categoryCol = "PRINCIPAL.IMPORTS", categoryValues = c("Self-propelled bulldozers, angledozers, graders, levellers, scrapers, mechanical shovels, excavators, shovel loaders, tamping machines and road rollers"))

dataProcessingMachinesPrincipleImports <- calculateStatValueSum(processedTradeStats, codes_CP4 = c(4000, 4071, 7100), categoryCol = "PRINCIPAL.IMPORTS", categoryValues = c("Automatic data processing machines; magnetic or optical readers, machines for transcribing data onto data media in coded form and machines for processing such data."))

electricConvertersPrincipleImports <- calculateStatValueSum(processedTradeStats, codes_CP4 = c(4000, 4071, 7100), categoryCol = "PRINCIPAL.IMPORTS", categoryValues = c("Electric generating sets and rotary converters"))

telephonePrincipleImports <- calculateStatValueSum(processedTradeStats, codes_CP4 = c(4000, 4071, 7100), categoryCol = "PRINCIPAL.IMPORTS", categoryValues = c("Telephone sets, including telephones for cellular networks or for other wireless networks"))

telephonePrincipleImports <- calculateStatValueSum(processedTradeStats, codes_CP4 = c(4000, 4071, 7100), categoryCol = "PRINCIPAL.IMPORTS", categoryValues = c("Telephone sets, including telephones for cellular networks or for other wireless networks")) 

conductorsPrincipleImports <- calculateStatValueSum(processedTradeStats, codes_CP4 = c(4000, 4071, 7100), categoryCol = "PRINCIPAL.IMPORTS", categoryValues = c("Insulated wire, cable and other insulated electric conductors, whether or not fitted with connectors; optical fibre cables, made up of individually sheathed fibres, whether or not assembled with electric conductors or fitted with connectors")) 

conductorsPrincipleImports <- calculateStatValueSum(processedTradeStats, codes_CP4 = c(4000, 4071, 7100), categoryCol = "PRINCIPAL.IMPORTS", categoryValues = c("Insulated wire, cable and other insulated electric conductors, whether or not fitted with connectors; optical fibre cables, made up of individually sheathed fibres, whether or not assembled with electric conductors or fitted with connectors")) 

motorVehiclesPassengersPrincipleImports <- calculateStatValueSum(processedTradeStats, codes_CP4 = c(4000, 4071, 7100), categoryCol = "PRINCIPAL.IMPORTS", categoryValues = c("Motor vehicles for the transport of passengers")) 

motorVehiclesGoodsPrincipleImports <- calculateStatValueSum(processedTradeStats, codes_CP4 = c(4000, 4071, 7100), categoryCol = "PRINCIPAL.IMPORTS", categoryValues = c("Motor vehicles for the transport of goods")) 

partsAircraftPrincipleImports <- calculateStatValueSum(processedTradeStats, codes_CP4 = c(4000, 4071, 7100), categoryCol = "PRINCIPAL.IMPORTS", categoryValues = c("Parts of aircraft")) 

yachtsPrincipleImports <- calculateStatValueSum(processedTradeStats, codes_CP4 = c(4000, 4071, 7100), categoryCol = "PRINCIPAL.IMPORTS", categoryValues = c("Yachts and other vessels for pleasure or sports; rowing boats and canoes"))

furniturePrincipleImports <- calculateStatValueSum(processedTradeStats, codes_CP4 = c(4000, 4071, 7100), categoryCol = "PRINCIPAL.IMPORTS", categoryValues = c("Other furniture and parts thereof"))

personalEffectsPrincipleImports <- calculateStatValueSum(processedTradeStats, codes_CP4 = c(4000, 4071, 7100), categoryCol = "PRINCIPAL.IMPORTS", categoryValues = c("Personal and household effects"))

otherPrincipleImports <- calculateStatValueSum(processedTradeStats, codes_CP4 = c(4000, 4071, 7100), categoryCol = "PRINCIPAL.IMPORTS", categoryValues = c("Other Imports"))

totalPImports<- meatPrincipleImports + fishPrincipleImports + milkPrincipleImports + ricePrincipleImports + wheatPrincipleImports + preparedMeatPrincipleImports + preparedFishPrincipleImports + sugarPrincipleImports + pastaPrincipleImports + preparedFoodsPrincipleImports + breadPrincipleImports + nonAlcoholicPrincipleImports + alcoholicPrincipleImports + animalFeedingPrincipleImports + tobaccoProductsPrincipleImports + cementPrincipleImports + petroleumPrincipleImports + hydrocarbonsPrincipleImports + medicamentsPrincipleImports + perfumesPrincipleImports + pipesPrincipleImports + lidsPrincipleImports + tiresPrincipleImports + woodPrincipleImports + toiletPaperPrincipleImports + printedBooksPrincipleImports + clothingPrincipleImports + textileClothingPrincipleImports + footwearPrincipleImports + ironSteelPrincipleImports + articlesIronSteelPrincipleImports + aluminiumThereofPrincipleImports + enginesThereofPrincipleImports + refridgeratorsPrincipleImports + purifyingMachineryPrincipleImports + bulldozersPrincipleImports + dataProcessingMachinesPrincipleImports + electricConvertersPrincipleImports + telephonePrincipleImports + conductorsPrincipleImports + motorVehiclesPassengersPrincipleImports + motorVehiclesGoodsPrincipleImports + partsAircraftPrincipleImports + yachtsPrincipleImports + furniturePrincipleImports + personalEffectsPrincipleImports + otherPrincipleImports


# Insert values into table
totalPrincipleImports <- data.frame("Meat and edible offal of poultry"= meatPrincipleImports, 
                                    "Fish and crustaceans, molluscs and other aquatic invertebrates"= fishPrincipleImports, 
                                    "Milk and Cream"= milkPrincipleImports, 
                                    "Rice"= ricePrincipleImports, 
                                    "Wheat or meslin flour"= wheatPrincipleImports, 
                                    "Other prepared or preserved meat, meat offal or blood"= preparedMeatPrincipleImports, 
                                    "Prepared or preserved fish"= preparedFishPrincipleImports, 
                                    "Sugar"= sugarPrincipleImports, 
                                    "Pasta, whether cooked or stuffed or otherwise prepared, such as spaghetti, macaroni, noodles, lasagne, gnocchi, ravioli, cannelloni; couscous"= pastaPrincipleImports, 
                                    "Prepared foods obtained by the swelling or roasting of cereals or cereal products eg corn flakes; cereals (excl maize) in grain or flakes"= preparedFoodsPrincipleImports, 
                                    "Bread, pastry, cakes, biscuits and other bakers' wares"= breadPrincipleImports, 
                                    "Non-alcoholic drinks including mineral water"= nonAlcoholicPrincipleImports, 
                                    "Alcoholic drinks"= alcoholicPrincipleImports, 
                                    "Preparations of a kind used in animal feeding"= animalFeedingPrincipleImports, 
                                    "Cigars, cheroots, cigarillos and cigarettes, of tobacco or of tobacco substitutes"= tobaccoProductsPrincipleImports, 
                                    "Portland cement, aluminous cement, slag cement, supersulphate cement and similar hydraulic cements"= cementPrincipleImports, 
                                    "Petroleum oils and oils obtained from bituminous minerals"= petroleumPrincipleImports, 
                                    "Petroleum gases and other gaseous hydrocarbons"= hydrocarbonsPrincipleImports, 
                                    "Medicaments"= medicamentsPrincipleImports, 
                                    "Perfumes, make-up preparations and preparations for the care of the skin (excl medicaments) and products for hair"= perfumesPrincipleImports, 
                                    "Tubes, pipes and hoses, and fittings therefor (for example, joints, elbows, flanges), of plastics."= pipesPrincipleImports, 
                                    "Articles for the conveyance or packing of goods; stoppers, lids, caps and other closures, of plastics"= lidsPrincipleImports, 
                                    "New pneumatic tires, of rubber"= tiresPrincipleImports, 
                                    "Wood sawn or chipped lengthwise, sliced or peeled, whether or not planed, sanded or end-jointed"= woodPrincipleImports, 
                                    "Toilet paper and similar paper"= toiletPaperPrincipleImports, 
                                    "Printed books, brochures, leaflets and similar printed matter"= printedBooksPrincipleImports, 
                                    "Articles of apparel and clothing accessories"= clothingPrincipleImports, 
                                    "Other made up textile articles; sets; worn clothing and worn textile articles; rags"= textileClothingPrincipleImports, 
                                    "Footwear, gaiters and the like; parts of such articles"= footwearPrincipleImports, 
                                    "Iron and steel"= ironSteelPrincipleImports, 
                                    "Articles of iron or steel"= articlesIronSteelPrincipleImports, 
                                    "Aluminium and articles thereof"= aluminiumThereofPrincipleImports, 
                                    "Spark-ignition reciprocating or rotary internal combustion piston engines and compression-ignition internal combustion piston engines (diesel or semi-diesel engines)"= enginesThereofPrincipleImports, 
                                    "Refrigerators, freezers and other refrigerating or freezing equipment, electric or other; heat pumps other than air conditioning machines"= refridgeratorsPrincipleImports, 
                                    "Centrifuges, including centrifugal dryers; filtering or purifying machinery and apparatus, for liquids or gases"= purifyingMachineryPrincipleImports, 
                                    "Self-propelled bulldozers, angledozers, graders, levellers, scrapers, mechanical shovels, excavators, shovel loaders, tamping machines and road rollers"= bulldozersPrincipleImports, 
                                    "Automatic data processing machines; magnetic or optical readers, machines for transcribing data onto data media in coded form and machines for processing such data."= dataProcessingMachinesPrincipleImports, 
                                    "Electric generating sets and rotary converters"= electricConvertersPrincipleImports, 
                                    "Telephone sets, including telephones for cellular networks or for other wireless networks"= telephonePrincipleImports, 
                                    "Insulated wire, cable and other insulated electric conductors, whether or not fitted with connectors; optical fibre cables, made up of individually sheathed fibres, whether or not assembled with electric conductors or fitted with connectors"= conductorsPrincipleImports, 
                                    "Motor vehicles for the transport of passengers"= motorVehiclesPassengersPrincipleImports, 
                                    "Motor vehicles for the transport of goods"= motorVehiclesGoodsPrincipleImports, 
                                    "Parts of aircraft"= partsAircraftPrincipleImports, 
                                    "Yachts and other vessels for pleasure or sports; rowing boats and canoes"= yachtsPrincipleImports, 
                                    "Other furniture and parts thereof"= furniturePrincipleImports, 
                                    "Personal and household effects"= personalEffectsPrincipleImports, 
                                    "Other Imports"= otherPrincipleImports, 
                                    "TOTAL IMPORTS"= totalPImports) 

prettyTable(totalPrincipleImports)




```

```{r insert Principle Imports into final formatted table}

```


## Balance of Trade by Major Partner Countries
```{r calculate balance of trade by major partner countries statistics with base R, eval=FALSE, echo=FALSE}

# Calculate the Balance of Trade by Major Partner Countries

australiaExports <- calculateStatValueSum(processedTradeStats, codes_CP4 = c(1000, 3071), categoryCol ="COUNTRY", categoryValues = c("AUSTRALIA"))
australiaImports <- calculateStatValueSum(processedTradeStats, codes_CP4 = c(000, 4071, 7100), categoryCol ="COUNTRY", categoryValues = c("AUSTRALIA"))
australiaTradeBalance<- australiaExports - australiaImports

chinaExports <- calculateStatValueSum(processedTradeStats, codes_CP4 = c(1000, 3071), categoryCol = "COUNTRY", categoryValues = c("CHINA, PEOPLES REPUBLIC OF"))
chinaImports <- calculateStatValueSum(processedTradeStats, codes_CP4 = c(000, 4071, 7100), categoryCol = "COUNTRY", categoryValues = c("CHINA, PEOPLES REPUBLIC OF"))
chinaTradeBalance<- chinaExports - chinaImports

fijiExports <- calculateStatValueSum(processedTradeStats, codes_CP4 = c(1000, 3071), categoryCol = "COUNTRY", categoryValues = c("FIJI"))
fijiImports <- calculateStatValueSum(processedTradeStats, codes_CP4 = c(000, 4071, 7100), categoryCol = "COUNTRY", categoryValues = c("FIJI"))
fijiTradeBalance<- fijiExports - fijiImports

franceExports <- calculateStatValueSum(processedTradeStats, codes_CP4 = c(1000, 3071), categoryCol = "COUNTRY", categoryValues = c("FRANCE"))
franceImports <- calculateStatValueSum(processedTradeStats, codes_CP4 = c(000, 4071, 7100), categoryCol = "COUNTRY", categoryValues = c("FRANCE"))
franceTradeBalance<- franceExports - franceImports
	
hongkongExports <- calculateStatValueSum(processedTradeStats, codes_CP4 = c(1000, 3071), categoryCol = "COUNTRY", categoryValues = c("HONG KONG"))
hongkongImports <- calculateStatValueSum(processedTradeStats, codes_CP4 = c(000, 4071, 7100), categoryCol = "COUNTRY", categoryValues = c("HONG KONG"))
hongkongTradeBalance<- hongkongExports - hongkongImports

indiaExports <- calculateStatValueSum(processedTradeStats, codes_CP4 = c(1000, 3071), categoryCol = "COUNTRY", categoryValues = c("INDIA"))
indiaImports <- calculateStatValueSum(processedTradeStats, codes_CP4 = c(000, 4071, 7100), categoryCol = "COUNTRY", categoryValues = c("INDIA"))
indiaTradeBalance<- indiaExports - indiaImports

indonesiaExports <- calculateStatValueSum(processedTradeStats, codes_CP4 = c(1000, 3071), categoryCol = "COUNTRY", categoryValues = c("INDONESIA"))
indonesiaImports <- calculateStatValueSum(processedTradeStats, codes_CP4 = c(000, 4071, 7100), categoryCol = "COUNTRY", categoryValues = c("INDONESIA"))
indonesiaTradeBalance<- indonesiaExports - indonesiaImports

japanExports <- calculateStatValueSum(processedTradeStats, codes_CP4 = c(1000, 3071), categoryCol = "COUNTRY", categoryValues = c("JAPAN"))
japanImports <- calculateStatValueSum(processedTradeStats, codes_CP4 = c(000, 4071, 7100), categoryCol = "COUNTRY", categoryValues = c("JAPAN"))
japanTradeBalance<- japanExports - japanImports

koreaExports <- calculateStatValueSum(processedTradeStats, codes_CP4 = c(1000, 3071), categoryCol = "COUNTRY", categoryValues = c("KOREA, REPUBLIC OF"))
koreaImports <- calculateStatValueSum(processedTradeStats, codes_CP4 = c(000, 4071, 7100), categoryCol = "COUNTRY", categoryValues = c("KOREA, REPUBLIC OF"))
koreaTradeBalance<- koreaExports - koreaImports

malaysiaExports <- calculateStatValueSum(processedTradeStats, codes_CP4 = c(1000, 3071), categoryCol = "COUNTRY", categoryValues = c("MALAYSIA"))
malaysiaImports <- calculateStatValueSum(processedTradeStats, codes_CP4 = c(000, 4071, 7100), categoryCol = "COUNTRY", categoryValues = c("MALAYSIA"))
malaysiaTradeBalance<- malaysiaExports - malaysiaImports

netherlandsExports <- calculateStatValueSum(processedTradeStats, codes_CP4 = c(1000, 3071), categoryCol = "COUNTRY", categoryValues = c("NETHERLANDS"))
netherlandsImports <- calculateStatValueSum(processedTradeStats, codes_CP4 = c(000, 4071, 7100), categoryCol = "COUNTRY", categoryValues = c("NETHERLANDS"))
netherlandsTradeBalance<- netherlandsExports - netherlandsImports

netherlandsExports <- calculateStatValueSum(processedTradeStats, codes_CP4 = c(1000, 3071), categoryCol = "COUNTRY", categoryValues = c("NETHERLANDS"))
netherlandsImports <- calculateStatValueSum(processedTradeStats, codes_CP4 = c(000, 4071, 7100), categoryCol = "COUNTRY", categoryValues = c("NETHERLANDS"))
netherlandsTradeBalance<- netherlandsExports - netherlandsImports

newCaledoniaExports <- calculateStatValueSum(processedTradeStats, codes_CP4 = c(1000, 3071), categoryCol = "COUNTRY", categoryValues = c("NEW CALEDONIA"))
newCaledoniaImports <- calculateStatValueSum(processedTradeStats, codes_CP4 = c(000, 4071, 7100), categoryCol = "COUNTRY", categoryValues = c("NEW CALEDONIA"))
newCaledoniaTradeBalance<- newCaledoniaExports - newCaledoniaImports

newZealandExports <- calculateStatValueSum(processedTradeStats, codes_CP4 = c(1000, 3071), categoryCol = "COUNTRY", categoryValues = c("NEW ZEALAND"))
newZealandImports <- calculateStatValueSum(processedTradeStats, codes_CP4 = c(000, 4071, 7100), categoryCol = "COUNTRY", categoryValues = c("NEW ZEALAND"))
newZealandTradeBalance<- newZealandExports - newZealandImports

papuaNewGuineaExports <- calculateStatValueSum(processedTradeStats, codes_CP4 = c(1000, 3071), categoryCol = "COUNTRY", categoryValues = c("PAPUA NEW GUINEA"))
papuaNewGuineaImports <- calculateStatValueSum(processedTradeStats, codes_CP4 = c(000, 4071, 7100), categoryCol = "COUNTRY", categoryValues = c("PAPUA NEW GUINEA"))
papuaNewGuineaTradeBalance<- papuaNewGuineaExports - papuaNewGuineaImports

philippinesExports <- calculateStatValueSum(processedTradeStats, codes_CP4 = c(1000, 3071), categoryCol = "COUNTRY", categoryValues = c("PHILIPPINES"))
philippinesImports <- calculateStatValueSum(processedTradeStats, codes_CP4 = c(000, 4071, 7100), categoryCol = "COUNTRY", categoryValues = c("PHILIPPINES"))
philippinesTradeBalance<- philippinesExports - philippinesImports

singaporeExports <- calculateStatValueSum(processedTradeStats, codes_CP4 = c(1000, 3071), categoryCol = "COUNTRY", categoryValues = c("SINGAPORE"))
singaporeImports <- calculateStatValueSum(processedTradeStats, codes_CP4 = c(000, 4071, 7100), categoryCol = "COUNTRY", categoryValues = c("SINGAPORE"))
singaporeTradeBalance<- singaporeExports - singaporeImports

solomonIslandsExports <- calculateStatValueSum(processedTradeStats, codes_CP4 = c(1000, 3071), categoryCol = "COUNTRY", categoryValues = c("SOLOMON ISLANDS"))
solomonIslandsImports <- calculateStatValueSum(processedTradeStats, codes_CP4 = c(000, 4071, 7100), categoryCol = "COUNTRY", categoryValues = c("SOLOMON ISLANDS"))
solomonIslandsTradeBalance<- solomonIslandsExports - solomonIslandsImports

thailandExports <- calculateStatValueSum(processedTradeStats, codes_CP4 = c(1000, 3071), categoryCol = "COUNTRY", categoryValues = c("THAILAND"))
thailandImports <- calculateStatValueSum(processedTradeStats, codes_CP4 = c(000, 4071, 7100), categoryCol = "COUNTRY", categoryValues = c("THAILAND"))
thailandTradeBalance<- thailandExports - thailandImports

ukExports <- calculateStatValueSum(processedTradeStats, codes_CP4 = c(1000, 3071), categoryCol = "COUNTRY", categoryValues = c("UNITED KINGDOM"))
ukImports <- calculateStatValueSum(processedTradeStats, codes_CP4 = c(000, 4071, 7100), categoryCol = "COUNTRY", categoryValues = c("UNITED KINGDOM"))
ukTradeBalance<- ukExports - ukImports

americaExports <- calculateStatValueSum(processedTradeStats, codes_CP4 = c(1000, 3071), categoryCol = "COUNTRY", categoryValues = c("UNITED STATES OF AMERICA"))
americaImports <- calculateStatValueSum(processedTradeStats, codes_CP4 = c(000, 4071, 7100), categoryCol = "COUNTRY", categoryValues = c("UNITED STATES OF AMERICA"))
americaTradeBalance<- americaExports - americaImports

allOthersExports <- calculateStatValueSum(processedTradeStats, codes_CP4 = c(1000, 3071), categoryCol = "COUNTRY", categoryValues = c("ALL OTHERS"))
allOthersImports <- calculateStatValueSum(processedTradeStats, codes_CP4 = c(000, 4071, 7100), categoryCol = "COUNTRY", categoryValues = c("ALL OTHERS"))
allOthersTradeBalance<- allOthersExports - allOthersImports

totalPCExports<- australiaExports + chinaExports + fijiExports + franceExports + hongkongExports + indiaExports + indonesiaExports + japanExports + koreaExports + malaysiaExports + netherlandsExports + newCaledoniaExports + newZealandExports + papuaNewGuineaExports + philippinesExports + singaporeExports + solomonIslandsExports + thailandExports + ukExports + americaExports + allOthersExports

totalPCImports<- australiaImports + chinaImports + fijiImports + franceImports + hongkongImports + indiaImports + indonesiaImports + japanImports + koreaImports + malaysiaImports + netherlandsImports + newCaledoniaImports + newZealandImports + papuaNewGuineaImports + philippinesImports + singaporeImports + solomonIslandsImports + thailandImports + ukImports + americaImports + allOthersImports

totalPCBalance<- totalPCExports - totalPCImports

# Insert values into table
balanceOfTradeByMajorPartnerCountries <- data.frame("Australia: Exports"=australiaExports, 
                                                    "Australia: Imports"=australiaImports, 
                                                    "Australia: Balance"= australiaBalance, 
                                                    "China, People's Republic of: Exports"=chinaExports, 
                                                    "China, People's Republic of: Imports"=chinaImports, 
                                                    "China, People's Republic of: Balance"= chinaBalance, 
                                                    "Fiji: Exports"=fijiExports, 
                                                    "Fiji: Imports"=fijiImports, 
                                                    "Fiji: Balance"= fijiBalance, 
                                                    "France: Exports"=franceExports, 
                                                    "France: Imports"=franceImports, 
                                                    "France: Balance"= franceBalance, 
                                                    "Hong Kong: Exports"=hongkongExports, 
                                                    "Hong Kong: Imports"=hongkongImports, 
                                                    "Hong Kong: Balance"= hongkongBalance, 
                                                    "India: Exports"=indiaExports, 
                                                    "India: Imports"=indiaImports, 
                                                    "India: Balance"= indiaBalance, 
                                                    "Indonesia: Exports"=indonesiaExports, 
                                                    "Indonesia: Imports"=indonesiaImports, 
                                                    "Indonesia: Balance"= indonesiaBalance, 
                                                    "Japan: Exports"=japanExports, 
                                                    "Japan: Imports"=japanImports, 
                                                    "Japan: Balance"= japanBalance, 
                                                    "Korea, Republic of: Exports"=koreaExports, 
                                                    "Korea, Republic of: Imports"=koreaImports, 
                                                    "Korea, Republic of: Balance"= koreaBalance, 
                                                    "Malaysia: Exports"=malaysiaExports, 
                                                    "Malaysia: Imports"=malaysiaImports, 
                                                    "Malaysia: Balance"= malaysiaBalance, 
                                                    "Netherlands: Exports"=netherlandsExports, 
                                                    "Netherlands: Imports"=netherlandsImports, 
                                                    "Netherlands: Balance"= netherlandsBalance, 
                                                    "New Caledonia: Exports"=newCaledoniaExports, 
                                                    "New Caledonia: Imports"=newCaledoniaImports, 
                                                    "New Caledonia: Balance"= newCaledoniaBalance,
                                                    "New Zealand: Exports"=newZealandExports, 
                                                    "New Zealand: Imports"=newZealandImports, 
                                                    "New Zealand: Balance"= newZealandBalance, 
                                                    "Papua NEW Guinea: Exports"=papuaNewGuineaExports, 
                                                    "Papua New Guinea: Imports"=papuaNewGuineaImports, 
                                                    "Papua New Guinea: Balance"= papuaNewGuineaBalance, 
                                                    "Philippines: Exports"=philippinesExports, 
                                                    "Philippines: Imports"=philippinesImports, 
                                                    "Philippines: Balance"= philippinesBalance, 
                                                    "Singapore: Exports"=singaporeExports, 
                                                    "Singapore: Imports"=singaporeImports, 
                                                    "Singapore: Balance"= singaporeBalance, 
                                                    "Solomon Islands: Exports"=solomonIslandsExports, 
                                                    "Solomon Islands: Imports"=solomonIslandsImports, 
                                                    "Solomon Islands: Balance"= solomonIslandsBalance, 
                                                    "Solomon Islands: Exports"=solomonIslandsExports, 
                                                    "Solomon Islands: Imports"=solomonIslandsImports, 
                                                    "Solomon Islands: Balance"= solomonIslandsBalance, 
                                                    "Thailand: Exports"=thailandExports, 
                                                    "Thailand: Imports"=thailandImports, 
                                                    "thailand: Balance"= thailandBalance, 
                                                    "United Kingdon: Exports"=ukExports, 
                                                    "United Kingdom: Imports"=ukImports, 
                                                    "United Kingdom: Balance"= ukBalance, 
                                                    "United States of America: Exports"=americaExports, 
                                                    "United States of America: Imports"=americaImports, 
                                                    "United States of America: Balance"= americaBalance, 
                                                    "All Others: Exports"=allOthersExports, 
                                                    "All Others: Imports"=allOthersImports, 
                                                    "All Others: Balance"= allOthersBalance, 
                                                    "Total: Exports"=totalPCExports, 
                                                    "Total: Imports"=totalPCImports, 
                                                    "Total: Balance"= totalPCBalance)
                                                    
prettyTable(balanceOfTradeByMajorPartnerCountries)

```

```{r insert balance of trade by major partner countries into final formatted table}


```


## Balance of Trade by Region
```{r calculate balance of trade by region statistics with base R, eval=FALSE, echo=FALSE}

# Calculate the Balance of Trade by Region
africaExports <- calculateStatValueSum(processedTradeStats, codes_CP4 = c(1000, 3071), categoryCol = "REGION", categoryValues = c("AFRICA"))
africaImports <- calculateStatValueSum(processedTradeStats, codes_CP4 = c(4000, 4071, 7100), categoryCol = "REGION", categoryValues = c("AFRICA"))
africaBalance<- africaExports - africaImports

theAmericasExports <- calculateStatValueSum(processedTradeStats, codes_CP4 = c(1000, 3071), categoryCol = "REGION", categoryValues = c("AMERICAS"))
theAmericasImports <- calculateStatValueSum(processedTradeStats, codes_CP4 = c(4000, 4071, 7100), categoryCol = "REGION", categoryValues = c("AMERICAS"))
theAmericasBalance<- theAmericasExports - theAmericasImports

asiaExports <- calculateStatValueSum(processedTradeStats, codes_CP4 = c(1000, 3071), categoryCol = "REGION", categoryValues = c("ASIA"))
asiaImports <- calculateStatValueSum(processedTradeStats, codes_CP4 = c(4000, 4071, 7100), categoryCol = "REGION", categoryValues = c("ASIA"))
asiaBalance<- asiaExports - asiaImports

europeExports <- calculateStatValueSum(processedTradeStats, codes_CP4 = c(1000, 3071), categoryCol = "REGION", categoryValues = c("EUROPE"))
europeImports <- calculateStatValueSum(processedTradeStats, codes_CP4 = c(4000, 4071, 7100), categoryCol = "REGION", categoryValues = c("EUROPE"))
europeBalance<- europeExports - europeImports

oceaniaExports <- calculateStatValueSum(processedTradeStats, codes_CP4 = c(1000, 3071), categoryCol = "REGION", categoryValues = c("OCEANIA"))
oceaniaImports <- calculateStatValueSum(processedTradeStats, codes_CP4 = c(4000, 4071, 7100), categoryCol = "REGION", categoryValues = c("OCEANIA"))
oceaniaBalance<- oceaniaExports - oceaniaImports

variousExports <- calculateStatValueSum(processedTradeStats, codes_CP4 = c(1000, 3071), categoryCol = "REGION", categoryValues = c("VARIOUS"))
variousImports <- calculateStatValueSum(processedTradeStats, codes_CP4 = c(4000, 4071, 7100), categoryCol = "REGION", categoryValues = c("VARIOUS"))
variousBalance<- variousExports - variousImports

totalRegionExports<- africaExports + theAmericasExports + asiaExports + europeExports + oceaniaExports + variousExports
totalRegionImports<- africaImports + theAmericasImports + asiaImports + europeImports + oceaniaImports + variousImports
totalRegionBalance<- totalRegionExports - totalRegionImports

pictsExports<- oceaniaExports - australiaExports - newZealandExports
pictsImports<- oceaniaImports - australiaImports - newZealandImports
pictsBalance<- oceaniaBalance - australiaBalance - newZealandBalance


# Insert values into table
balanceOfTradeByRegion <- data.frame("Africa: Exports"=africaExports, 
                                     "Africa: Imports"=africaImports, 
                                     "Africa: Balance"= africaBalance, 
                                     "The Americas: Exports"=theAmericasExports, 
                                     "The Americas: Imports"=theAmericasImports, 
                                     "The Americas: Balance"= theAmericasBalance, 
                                     "Asia: Exports"=asiaExports, 
                                     "Asia: Imports"=asiaImports, 
                                     "Asia: Balance"= asiaBalance, 
                                     "Europe: Exports"=europeExports, 
                                     "Europe: Imports"=europeImports, 
                                     "Europe: Balance"= europeBalance, 
                                     "Oceania: Exports"=oceaniaExports, 
                                     "Oceania: Imports"=oceaniaImports, 
                                     "Oceania: Balance"= oceaniaBalance, 
                                     "Various: Exports"=variousExports, 
                                     "Various: Imports"=variousImports, 
                                     "Various: Balance"= variousBalance, 
                                     "Total: Exports"=totalRegionExports, 
                                     "Total: Imports"=totalRegionImports, 
                                     "Total: Balance"= totalRegionBalance, 
                                     "of which the PICTs: Exports"=pictsExports, 
                                     "of which the PICTs: Imports"=pictsImports, 
                                     "of which the PICTs: Balance"= pictsBalance)
                                                    
prettyTable(balanceOfTradeByRegion)

```

```{r insert balance of trade by Region into final formatted table}


```


## Trade by Mode of Transport 
```{r calculate trade by mode of transport statistics with base R, eval=FALSE, echo=FALSE}

# Calculate Trade by Mode of Transport

airExports <- calculateStatValueSum(processedTradeStats, codes_CP4 = c(1000, 3071), categoryCol = "Mode.of.Transport", categoryValues = c("AIR"))
airImports <- calculateStatValueSum(processedTradeStats, codes_CP4 = c(4000, 4071, 7100), categoryCol = "Mode.of.Transport", categoryValues = c("AIR"))

waterExports <- calculateStatValueSum(processedTradeStats, codes_CP4 = c(1000, 3071), categoryCol = "Mode.of.Transport", categoryValues = c("WATER"))
waterImports <- calculateStatValueSum(processedTradeStats, codes_CP4 = c(4000, 4071, 7100), categoryCol = "Mode.of.Transport", categoryValues = c("WATER"))

landExports <- calculateStatValueSum(processedTradeStats, codes_CP4 = c(1000, 3071), categoryCol = "Mode.of.Transport", categoryValues = c("LAND"))
landImports <- calculateStatValueSum(processedTradeStats, codes_CP4 = c(4000, 4071, 7100), categoryCol = "Mode.of.Transport", categoryValues = c("LAND"))

postageExports <- calculateStatValueSum(processedTradeStats, codes_CP4 = c(1000, 3071), categoryCol = "Mode.of.Transport", categoryValues = c("POSTAL"))
postageImports <- calculateStatValueSum(processedTradeStats, codes_CP4 = c(4000, 4071, 7100), categoryCol = "Mode.of.Transport", categoryValues = c("POSTAL"))

otherTransportExports <- calculateStatValueSum(processedTradeStats, codes_CP4 = c(1000, 3071), categoryCol = "Mode.of.Transport", categoryValues = c("OTHERL"))
otherTransportImports <- calculateStatValueSum(processedTradeStats, codes_CP4 = c(4000, 4071, 7100), categoryCol = "Mode.of.Transport", categoryValues = c("OTHER"))

totalTransportExports<- airExports + waterExports + landExports + postageExports + otherTransportExports
totalTransportImports<- airImports + waterImports + landImports + postageImports + otherTransportImports

# Insert values into table
tradebyModeOfTransport <- data.frame("Air: Exports"=airExports, 
                                     "Air: Imports"=airImports, 
                                     "Water: Exports"=airExports, 
                                     "Water: Imports"=waterImports, 
                                     "Land: Exports"=landExports, 
                                     "Land: Imports"=landImports, 
                                     "Postal consignments, mail or courier: Exports"= postageExports, 
                                     "Postal consignments, mail or courier: Imports"= postageImports, 
                                     "Others: Exports"= otherTransportExports, "Others: Imports"= otherTransportImports, 
                                     "Total: Exports"= totalTransportExports, 
                                     "Total: Imports"= totalTransportImports)
                                                    
prettyTable(tradebyModeOfTransport)

```

```{r insert balance of trade by Region into final formatted table}


```